In [2]:
import pandas as pd

# SERIES

In [6]:
s = pd.Series([10,20,30,40,50])
s

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [8]:
s.dtype

dtype('int64')

In [10]:
s.values

array([10, 20, 30, 40, 50], dtype=int64)

In [12]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
s.name = "calories"
s.name

'calories'

In [35]:
s

0    10
1    20
2    30
3    40
4    50
Name: calories, dtype: int64

# a-Indexing

In [38]:
s[0]

10

In [40]:
s[0:2]

0    10
1    20
Name: calories, dtype: int64

In [42]:
s[2:4]

2    30
3    40
Name: calories, dtype: int64

In [44]:
# location based indexing 
s.iloc[3]

40

In [46]:
s.iloc[[1,3,4]]

1    20
3    40
4    50
Name: calories, dtype: int64

In [48]:
index = ["apple", "banana", "grapes", "orange", "strawberry"]

In [50]:
s.index = index 
s

apple         10
banana        20
grapes        30
orange        40
strawberry    50
Name: calories, dtype: int64

In [54]:
# Label based indexing
s.loc['grapes']

30

In [56]:
# in label based(loc) start and stop both are included

In [62]:
# dict

fruit_protein = {
    "Avocado": 2.0,       # grams of protein
    "Guava": 2.6,
    "Blackberries": 2.0,
    "Oranges": 0.9,
    "Banana": 1.1,
    "Apples": 0.3,
    "Kiwi": 1.1,
    "Pomegranate": 1.7,
    "Mango": 0.8,
    "Cherries": 1.0
}

In [66]:
s2  = pd.Series(fruit_protein, name = "Protein")
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [70]:
s2.loc[['Avocado', 'Apples']]

Avocado    2.0
Apples     0.3
Name: Protein, dtype: float64

In [74]:
s2.iloc[[1,2,3,4]]

Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Name: Protein, dtype: float64

# b-Conditional Selection

In [77]:
s2 > 1

Avocado          True
Guava            True
Blackberries     True
Oranges         False
Banana           True
Apples          False
Kiwi             True
Pomegranate      True
Mango           False
Cherries        False
Name: Protein, dtype: bool

In [79]:
s2[s2>1]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Banana          1.1
Kiwi            1.1
Pomegranate     1.7
Name: Protein, dtype: float64

 # c-Logical Operations   (and - or - not)

In [101]:
[(s2 > 0.5) & (s2 < 2)]

[Avocado         False
 Guava           False
 Blackberries    False
 Oranges          True
 Banana           True
 Apples          False
 Kiwi             True
 Pomegranate      True
 Mango            True
 Cherries         True
 Name: Protein, dtype: bool]

In [103]:
s2[(s2 > 0.5) & (s2 < 2)]

Oranges        0.9
Banana         1.1
Kiwi           1.1
Pomegranate    1.7
Mango          0.8
Cherries       1.0
Name: Protein, dtype: float64

In [105]:
s2[(s2>0.5) | (s2 <= 2)]

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           0.8
Cherries        1.0
Name: Protein, dtype: float64

In [107]:
# not operation:

s2[~(s2>1)]

Oranges     0.9
Apples      0.3
Mango       0.8
Cherries    1.0
Name: Protein, dtype: float64

# d-Modifying the series

In [120]:
s2["Mango"] = 2.8
s2

Avocado         2.0
Guava           2.6
Blackberries    2.0
Oranges         0.9
Banana          1.1
Apples          0.3
Kiwi            1.1
Pomegranate     1.7
Mango           2.8
Cherries        1.0
Name: Protein, dtype: float64

In [125]:
import numpy as np

In [133]:
ser = pd.Series(['a', np.nan, 1, np.nan, 2])
ser.notnull().sum()

3

# DATAFRAME

In [135]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Alice"],
    "Age": [25, 30, 35, np.nan, 29, 25],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "HR"],
    "Salary": [50000, 60000, 70000, 62000, np.nan, 50000]
}

In [137]:
df = pd.DataFrame(data)
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [139]:
df.head()

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN

 # loc and iloc

In [142]:
df.iloc[1:3, :2]

      Name   Age
1      Bob  30.0
2  Charlie  35.0

In [144]:
df.loc[1:2, ["Age","Department"]]

    Age Department
1  30.0         IT
2  35.0    Finance

In [146]:
df[["Age", "Department"]]

    Age Department
0  25.0         HR
1  30.0         IT
2  35.0    Finance
3   NaN         IT
4  29.0         HR
5  25.0         HR

In [148]:
df.drop("Age", axis = 1)

      Name Department   Salary
0    Alice         HR  50000.0
1      Bob         IT  60000.0
2  Charlie    Finance  70000.0
3    David         IT  62000.0
4      Eve         HR      NaN
5    Alice         HR  50000.0

In [150]:
df

      Name   Age Department   Salary
0    Alice  25.0         HR  50000.0
1      Bob  30.0         IT  60000.0
2  Charlie  35.0    Finance  70000.0
3    David   NaN         IT  62000.0
4      Eve  29.0         HR      NaN
5    Alice  25.0         HR  50000.0

In [152]:
df.shape

(6, 4)

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        6 non-null      object
 1   Age         5 non-null      float64
 2   Department  6 non-null      object
 3   Salary      5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes

In [160]:
df.describe()

             Age        Salary
count   5.000000      5.000000
mean   28.800000  58400.000000
std     4.147288   8532.291603
min    25.000000  50000.000000
25%    25.000000  50000.000000
50%    29.000000  60000.000000
75%    30.000000  62000.000000
max    35.000000  70000.000000

# broadcasting

In [171]:
df["Salary"] = df["Salary"] + 5000

In [173]:
df["Salary"]

0    56000.0
1    66000.0
2    76000.0
3    68000.0
4        NaN
5    56000.0
Name: Salary, dtype: float64

# renaming columns

In [178]:
df.rename(columns = {"Department" : "Dept"}, inplace = True)

In [180]:
df

      Name   Age     Dept   Salary
0    Alice  25.0       HR  56000.0
1      Bob  30.0       IT  66000.0
2  Charlie  35.0  Finance  76000.0
3    David   NaN       IT  68000.0
4      Eve  29.0       HR      NaN
5    Alice  25.0       HR  56000.0

In [182]:
df["Dept"].unique()

array(['HR', 'IT', 'Finance'], dtype=object)

In [188]:
df["Dept"].value_counts()

Dept
HR         3
IT         2
Finance    1
Name: count, dtype: int64

In [194]:
df["Promoted salary"] = df["Salary"] *  10

In [196]:
df

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  56000.0         560000.0
1      Bob  30.0       IT  66000.0         660000.0
2  Charlie  35.0  Finance  76000.0         760000.0
3    David   NaN       IT  68000.0         680000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  56000.0         560000.0

# data cleaning

In [199]:
df.isnull().sum()

Name               0
Age                1
Dept               0
Salary             1
Promoted salary    1
dtype: int64

In [201]:
df.dropna()

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  56000.0         560000.0
1      Bob  30.0       IT  66000.0         660000.0
2  Charlie  35.0  Finance  76000.0         760000.0
5    Alice  25.0       HR  56000.0         560000.0

In [203]:
df.dropna(how = "any")

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  56000.0         560000.0
1      Bob  30.0       IT  66000.0         660000.0
2  Charlie  35.0  Finance  76000.0         760000.0
5    Alice  25.0       HR  56000.0         560000.0

In [205]:
df.dropna(how = "all")

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  56000.0         560000.0
1      Bob  30.0       IT  66000.0         660000.0
2  Charlie  35.0  Finance  76000.0         760000.0
3    David   NaN       IT  68000.0         680000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  56000.0         560000.0

In [207]:
df

      Name   Age     Dept   Salary  Promoted salary
0    Alice  25.0       HR  56000.0         560000.0
1      Bob  30.0       IT  66000.0         660000.0
2  Charlie  35.0  Finance  76000.0         760000.0
3    David   NaN       IT  68000.0         680000.0
4      Eve  29.0       HR      NaN              NaN
5    Alice  25.0       HR  56000.0         560000.0

In [209]:
df["Age"].fillna(df["Age"].mean())

0    25.0
1    30.0
2    35.0
3    28.8
4    29.0
5    25.0
Name: Age, dtype: float64

In [211]:
df["Salary"].fillna(df["Salary"].median())

0    56000.0
1    66000.0
2    76000.0
3    68000.0
4    66000.0
5    56000.0
Name: Salary, dtype: float64

In [213]:
df["Name"] = df["Name"].replace("Charlie", "Rose")

In [215]:
df

    Name   Age     Dept   Salary  Promoted salary
0  Alice  25.0       HR  56000.0         560000.0
1    Bob  30.0       IT  66000.0         660000.0
2   Rose  35.0  Finance  76000.0         760000.0
3  David   NaN       IT  68000.0         680000.0
4    Eve  29.0       HR      NaN              NaN
5  Alice  25.0       HR  56000.0         560000.0

# duplicates

In [226]:
df_dup = df[df.duplicated (keep = "first")]

In [228]:
df_dup

    Name   Age Dept   Salary  Promoted salary
5  Alice  25.0   HR  56000.0         560000.0

In [230]:
df_dup = df[df.duplicated (keep = "last")]

In [232]:
df_dup

    Name   Age Dept   Salary  Promoted salary
0  Alice  25.0   HR  56000.0         560000.0

In [234]:
df = df.drop_duplicates()

In [236]:
df

    Name   Age     Dept   Salary  Promoted salary
0  Alice  25.0       HR  56000.0         560000.0
1    Bob  30.0       IT  66000.0         660000.0
2   Rose  35.0  Finance  76000.0         760000.0
3  David   NaN       IT  68000.0         680000.0
4    Eve  29.0       HR      NaN              NaN

# invalid values
## lambda

In [248]:
df["Promoted Salary"] = df["Promoted Salary"].where(
    df["Promoted Salary"] <= 650000,
    df["Promoted Salary"] / 10
)

KeyError: 'Promoted Salary'

In [250]:
df

    Name   Age     Dept   Salary  Promoted salary
0  Alice  25.0       HR  56000.0         560000.0
1    Bob  30.0       IT  66000.0         660000.0
2   Rose  35.0  Finance  76000.0         760000.0
3  David   NaN       IT  68000.0         680000.0
4    Eve  29.0       HR      NaN              NaN

# join and merges

In [255]:
department_info = {
    "Dept": ["HR", "IT", "Finance"],
    "Location": ["New York", "San Francisco", "Chicago"],
    "Manager": ["Laura", "Steve", "Nina"]
}

df2 = pd.DataFrame(department_info)
df2

      Dept       Location Manager
0       HR       New York   Laura
1       IT  San Francisco   Steve
2  Finance        Chicago    Nina

In [257]:
pd.merge(df, df2, on = "Dept")

    Name   Age     Dept   Salary  Promoted salary       Location Manager
0  Alice  25.0       HR  56000.0         560000.0       New York   Laura
1    Bob  30.0       IT  66000.0         660000.0  San Francisco   Steve
2   Rose  35.0  Finance  76000.0         760000.0        Chicago    Nina
3  David   NaN       IT  68000.0         680000.0  San Francisco   Steve
4    Eve  29.0       HR      NaN              NaN       New York   Laura